[project]
name = "image-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "python-multipart>=0.0.32",
    "rembg[cpu]>=2.0.84",
]

[project.optional-dependencies]
gui = ["pyside6>=6.11.2"]
